Feauture/fixing to date from date
rantNYC/TradeSimulator pull request #7
Opened 2022-01-10 00:10 UTC by nigel-heeral

2022-01-10 00:10 UTC, nigel-heeral commented
need integration testing

2022-01-11 21:44 UTC, rantNYC requested changes
Check my comments

2022-01-11 21:44 UTC, rantNYC commented on src/main/java/com/example/tradesimulator/controller/StockService.java
> +            //TODO: Custom exceptions, B I G Y I K E S
explain?

2022-01-11 21:44 UTC, rantNYC commented on src/main/java/com/example/tradesimulator/controller/StockService.java
> +                return Mono.error(e);
It's ok for now, but eventually we want different dates for each stock, so throwing error for the whole thing is not feasible

2022-01-11 21:44 UTC, rantNYC commented on src/main/java/com/example/tradesimulator/controller/StockService.java
> +                results.add(retrieveStockInfo(stock.getSymbol(), stockPayload.getFrom().substring(0,10), stockPayload.getTo().substring(0, 10)));
Should we pass the string to the function and let the function handle the validation? Thoughts

2022-01-11 21:44 UTC, rantNYC commented on src/main/java/com/example/tradesimulator/controller/StockService.java
> +        LocalDate from = LocalDate.parse(fromDate, DATE_FORMAT);
So, we dont need to parse it multiple times here

2022-01-11 21:44 UTC, rantNYC commented on src/main/java/com/example/tradesimulator/controller/StockService.java
> +        LocalDate start = LocalDate.parse(fromDate, DATE_FORMAT);
So, we dont need to parse it multiple times here

2022-01-11 21:44 UTC, rantNYC commented on src/main/java/com/example/tradesimulator/controller/StockService.java
> +        DayOfWeek day = DayOfWeek.of(ld.get(ChronoField.DAY_OF_WEEK));
Holidays still remain to be fixed

2022-01-11 21:44 UTC, rantNYC commented on src/main/java/com/example/tradesimulator/controller/StockService.java
> +            for (LocalDate date = start; !start.isAfter(end) && !date.isAfter(end); date = date.plusDays(1)) {
why do we need !start.isAfter(end), shouldnt start be always before end?

2022-01-11 22:03 UTC, nigel-heeral commented on src/main/java/com/example/tradesimulator/controller/StockService.java
> +            //TODO: Custom exceptions, B I G Y I K E S
Reee

2022-01-11 22:03 UTC, rantNYC approved these changes

2022-01-11 22:03 UTC, merged